# Utilisez une image de base contenant Node.js
FROM node:14 as build

# Définissez le répertoire de travail à l'intérieur du conteneur
WORKDIR /src/app

# Copiez package.json et package-lock.json dans le répertoire de travail
COPY package*.json ./

# Installez les dépendances du projet
RUN npm install

# Installez react-scripts globalement
RUN npm install -g react-scripts

# Copiez le reste des fichiers du projet dans le répertoire de travail
COPY . .

# Construisez l'application React pour la production
RUN npm run build

# Utilisez une image de base légère pour exécuter l'application React
FROM nginx:alpine

# Copiez les fichiers de build de l'application React dans le répertoire du serveur Nginx
COPY --from=build /src/app/build /usr/share/nginx/html

# Exposez le port sur lequel le serveur Nginx écoutera les requêtes
EXPOSE 80

# Démarrez le serveur Nginx
CMD ["nginx", "-g", "daemon off;"]